version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: chatbot_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend-network

  backend:
    build: .
    container_name: backend_container
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "./wait-for-it.sh db:3306 -- sh -c 'npx prisma generate && npx prisma db push && npm run start'"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
